import streamlit as st
import json
import base64

def generate_clinical_report_text(analysis, diagnosis, treatment_plan):
    """Generate a plain-text clinical report suitable for EHR copy-pasting."""
    if not diagnosis:
        return "No clinical data available."
        
    lines = []
    lines.append("CEPHALOMETRIC AI DIAGNOSTIC REPORT")
    lines.append("==================================")
    lines.append(f"Demographics: Age {diagnosis.get('age', 'N/A')}, Sex {diagnosis.get('sex', 'N/A')}")
    lines.append(f"Protocol: {diagnosis.get('protocol', 'Unknown')} : {diagnosis.get('protocol_version', 'Unknown')}")
    lines.append("\n[1] CLINICAL SUMMARY")
    lines.append(f"Skeletal Class: {diagnosis.get('skeletal_class', 'N/A')}")
    lines.append(f"Vertical Pattern: {diagnosis.get('vertical_pattern', 'N/A')}")
    lines.append(f"Severity: {str(diagnosis.get('severity', 'N/A')).title()}")
    lines.append(f"Dental Pattern: {str(diagnosis.get('dental_pattern', 'N/A')).capitalize()}")
    
    lines.append("\n[2] KEY FINDINGS & NARRATIVE")
    lines.append(diagnosis.get("professional_summary", "No summary available."))
    
    if treatment_plan:
        lines.append("\n[3] TREATMENT STRATEGY")
        primary = treatment_plan.get("primary_recommendation")
        if primary:
            lines.append(f"Primary Recommendation: {primary.get('title')}")
            lines.append(f"Rationale: {primary.get('rationale')}")
            lines.append(f"Timeline: {primary.get('timeline_months')} months")
            
        success = treatment_plan.get("success_prediction", {})
        if success:
            lines.append(f"Estimated Success Rate: {success.get('estimated_success_rate', 'Unknown')}")
            
    lines.append("\n[4] CEPHALOMETRIC MEASUREMENTS")
    measurements = analysis.get("measurements", [])
    for m in measurements:
        name = m.get("measurement", "Unknown")
        val = m.get("value", 0)
        norm = m.get("norm_mean", 0)
        stat = m.get("status", "normal")
        try:
            val = round(float(val), 2)
            norm = round(float(norm), 2)
        except:
            pass
        if stat != "normal":
            lines.append(f"  * {name}: {val} (Norm: {norm}) -> {stat.upper()}")
        else:
            lines.append(f"    {name}: {val} (Norm: {norm})")
            
    lines.append("\n==================================")
    lines.append("Generated by: Automated Cephalometric Analysis System")
    return "\n".join(lines)

def render_data_management_tab(landmarks: list):
    """Render export and save options with a clinical report generator."""
    if not landmarks:
        st.info("Run AI Analysis to manage data.")
        return

    analysis = st.session_state.get('analysis_results', {})
    diagnosis = st.session_state.get('diagnosis_results', {})
    treatment_plan = st.session_state.get('treatment_plan', {})

    col1, col2 = st.columns([1, 1])

    with col1:
        st.markdown(
            """
            <div style='background: rgba(255, 255, 255, 0.03); border: 1px solid rgba(255, 255, 255, 0.1); border-radius: 12px; padding: 1.5rem; height: 100%;'>
                <h3 style='margin-top: 0;'>📄 EHR Clinical Report</h3>
                <p style='color: #94a3b8; font-size: 0.9rem;'>
                    A plain-text summary of the AI findings, diagnosis, and treatment plan. 
                    Copy this directly into your patient management or EHR software.
                </p>
            """,
            unsafe_allow_html=True
        )
        
        report_text = generate_clinical_report_text(analysis, diagnosis, treatment_plan)
        st.code(report_text, language="markdown")
        st.markdown("</div>", unsafe_allow_html=True)

    with col2:
        st.markdown(
            """
            <div style='background: rgba(255, 255, 255, 0.03); border: 1px solid rgba(255, 255, 255, 0.1); border-radius: 12px; padding: 1.5rem; height: 100%;'>
                <h3 style='margin-top: 0;'>💾 Raw Data Exports</h3>
                <p style='color: #94a3b8; font-size: 0.9rem;'>
                    Export the comprehensive measurements and diagnostic trees for research or archival purposes.
                </p>
            """,
            unsafe_allow_html=True
        )
        
        st.markdown("#### JSON Full Export")
        export_data = {
            "landmarks": landmarks,
            "analysis": analysis,
            "diagnosis": diagnosis,
            "treatment_plan": treatment_plan
        }
        json_str = json.dumps(export_data, indent=2)
        st.download_button(
            label="⬇️ Download JSON Archive",
            data=json_str,
            file_name="ceph_full_analysis.json",
            mime="application/json",
            use_container_width=True
        )
        
        st.markdown("#### CSV Measurements")
        measurements = analysis.get("measurements", [])
        if measurements:
            import pandas as pd
            df = pd.DataFrame(measurements)
            csv = df.to_csv(index=False)
            st.download_button(
                label="⬇️ Download CSV Dataset",
                data=csv,
                file_name="ceph_measurements.csv",
                mime="text/csv",
                use_container_width=True
            )
        
        st.markdown("---")
        st.markdown("#### 💾 Local Repository")
        st.info("Save this patient case securely to the local SQLite database for future retrieval.")
        
        patient_id = st.text_input("Patient ID / Name", placeholder="e.g. JD-2023-01")
        comment = st.text_area("Clinical Notes (Optional)", placeholder="Add any specific observations here...")
        
        if st.button("Save Case to Database", use_container_width=True):
            if not patient_id:
                st.error("Please enter a Patient ID.")
            else:
                with st.spinner("Saving case..."):
                    from ..utils.api_client import create_case
                    payload = {
                        "landmarks": landmarks,
                        "px_to_mm": st.session_state.get("px_to_mm", 1.0),
                        "ethnic_profile": st.session_state.get("ethnic_profile", "Caucasian"),
                        "protocol_id": st.session_state.get("protocol_id", "core_lateral"),
                        "patient_identifier": patient_id,
                        "patient_age": st.session_state.get("patient_age"),
                        "patient_sex": st.session_state.get("patient_sex"),
                        "analysis_type": f"{st.session_state.get('protocol_id', 'core_lateral')} Analysis",
                        "status": "completed",
                        "comment": comment
                    }
                    res = create_case(payload)
                    if res and "case" in res:
                        st.success(f"Case successfully saved with ID: {res['case']['id']}")
                    else:
                        st.error("Failed to save case.")
            
        st.markdown("</div>", unsafe_allow_html=True)
