import json

import streamlit as st


def generate_clinical_report_text(analysis, diagnosis, treatment_plan):
    """Generate a plain-text clinical report suitable for EHR copy-pasting."""
    if not diagnosis:
        return "No clinical data available."

    lines = [
        "CEPHALOMETRIC AI DIAGNOSTIC REPORT",
        "==================================",
        f"Demographics: Age {diagnosis.get('age', 'N/A')}, Sex {diagnosis.get('sex', 'N/A')}",
        f"Protocol: {diagnosis.get('protocol', 'Unknown')} : {diagnosis.get('protocol_version', 'Unknown')}",
        "",
        "[1] CLINICAL SUMMARY",
        f"Skeletal Class: {diagnosis.get('skeletal_class', 'N/A')}",
        f"Vertical Pattern: {diagnosis.get('vertical_pattern', 'N/A')}",
        f"Severity: {str(diagnosis.get('severity', 'N/A')).title()}",
        f"Dental Pattern: {str(diagnosis.get('dental_pattern', 'N/A')).capitalize()}",
        "",
        "[2] KEY FINDINGS & NARRATIVE",
        diagnosis.get("professional_summary", "No summary available."),
    ]

    if treatment_plan:
        lines.extend(["", "[3] TREATMENT STRATEGY"])
        primary = treatment_plan.get("primary_recommendation")
        if primary:
            lines.append(f"Primary Recommendation: {primary.get('title')}")
            lines.append(f"Rationale: {primary.get('rationale')}")
            lines.append(f"Timeline: {primary.get('timeline_months')} months")

        success = treatment_plan.get("success_prediction", {})
        if success:
            lines.append(f"Estimated Success Rate: {success.get('estimated_success_rate', 'Unknown')}")

    lines.extend(["", "[4] CEPHALOMETRIC MEASUREMENTS"])
    for measurement in analysis.get("measurements", []):
        name = measurement.get("measurement", "Unknown")
        value = measurement.get("value", 0)
        norm = measurement.get("norm_mean", 0)
        status = measurement.get("status", "normal")
        try:
            value = round(float(value), 2)
            norm = round(float(norm), 2)
        except (TypeError, ValueError):
            pass

        marker = "*" if status != "normal" else " "
        suffix = f" -> {str(status).upper()}" if status != "normal" else ""
        lines.append(f"  {marker} {name}: {value} (Norm: {norm}){suffix}")

    lines.extend(["", "==================================", "Generated by: Automated Cephalometric Analysis System"])
    return "\n".join(lines)


def render_data_management_tab(landmarks: list):
    """Render export options with a clinical report generator."""
    if not landmarks:
        st.info("Run AI Analysis to manage data.")
        return

    analysis = st.session_state.get("analysis_results", {})
    diagnosis = st.session_state.get("diagnosis_results", {})
    treatment_plan = st.session_state.get("treatment_plan", {})

    col1, col2 = st.columns([1, 1])

    with col1:
        st.markdown(
            """
            <div style='background: rgba(255, 255, 255, 0.03); border: 1px solid rgba(255, 255, 255, 0.1); border-radius: 12px; padding: 1.5rem; height: 100%;'>
                <h3 style='margin-top: 0;'>EHR Clinical Report</h3>
                <p style='color: #94a3b8; font-size: 0.9rem;'>
                    A plain-text summary of the AI findings, diagnosis, and treatment plan.
                    Copy this directly into your patient management or EHR software.
                </p>
            """,
            unsafe_allow_html=True,
        )

        report_text = generate_clinical_report_text(analysis, diagnosis, treatment_plan)
        st.code(report_text, language="markdown")
        st.markdown("</div>", unsafe_allow_html=True)

    with col2:
        st.markdown(
            """
            <div style='background: rgba(255, 255, 255, 0.03); border: 1px solid rgba(255, 255, 255, 0.1); border-radius: 12px; padding: 1.5rem; height: 100%;'>
                <h3 style='margin-top: 0;'>Raw Data Exports</h3>
                <p style='color: #94a3b8; font-size: 0.9rem;'>
                    Export the measurements and diagnostic trees for research or archival purposes.
                </p>
            """,
            unsafe_allow_html=True,
        )

        st.markdown("#### JSON Full Export")
        export_data = {
            "landmarks": landmarks,
            "analysis": analysis,
            "diagnosis": diagnosis,
            "treatment_plan": treatment_plan,
        }
        st.download_button(
            label="Download JSON Archive",
            data=json.dumps(export_data, indent=2),
            file_name="ceph_full_analysis.json",
            mime="application/json",
            use_container_width=True,
        )

        st.markdown("#### CSV Measurements")
        measurements = analysis.get("measurements", [])
        if measurements:
            import pandas as pd

            csv = pd.DataFrame(measurements).to_csv(index=False)
            st.download_button(
                label="Download CSV Dataset",
                data=csv,
                file_name="ceph_measurements.csv",
                mime="text/csv",
                use_container_width=True,
            )

        st.markdown("</div>", unsafe_allow_html=True)
